version: "3.9"
services:
  localstack:
    image: localstack/localstack:3.7
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,dynamodb
      - DEBUG=1
      - DEFAULT_REGION=${AWS_REGION:-us-east-1}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.localstack}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"


